;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        cua-delete-region
        cua-paste
        markdown-cycle
        mykie:global-map:C-a:key
        mykie:global-map:C-e:key
        org-delete-char
        org-end-of-line
        org-return-indent
        org-self-insert-command
        sp--cua-replace-region
        sp--self-insert-command
        toggle-input-method
        ))

(setq mc/cmds-to-run-once
      '(
        ))
