;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        ac-pcmp/self-insert-command-with-ac-start
        c-electric-delete-forward
        c-electric-paren
        c-electric-semi&comma
        c-electric-slash
        cperl-electric-paren
        cperl-electric-rparen
        cperl-electric-semi
        cua-delete-region
        cua-paste
        electric-newline-and-maybe-indent
        elscreen-next
        elscreen-previous
        eshell-bol
        markdown-cycle
        mouse-buffer-menu
        mykie:global-map:C-a:key
        mykie:global-map:C-e:key
        mykie:global-map:C-w:key
        org-beginning-of-line
        org-delete-char
        org-end-of-line
        org-force-self-insert
        org-return-indent
        org-self-insert-command
        org-yank
        paredit-doublequote
        paredit-forward-delete
        paredit-open-round
        paredit-semicolon
        sp--cua-replace-region
        sp--self-insert-command
        toggle-input-method
        yas-expand
        ))

(setq mc/cmds-to-run-once
      '(
        ignore
        ))
